version: '3'

volumes:
    joplin-data:
    nginx_secrets:

services:
    app:
        image: florider89/joplin-server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
    db:
        image: postgres:13.1
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
        volumes:
            - joplin-data:/var/lib/postgresql/data
#            - ./pg_backup:/
    nginx:
        image: jonasal/nginx-certbot:latest
        restart: unless-stopped
        environment:
          - ${CERTBOT_EMAIL}
        ports:
          - 80:80
          - 443:443
        volumes:
          - nginx_secrets:/etc/letsencrypt
          - ./nginx:/etc/nginx/user_conf.d
